-- =============================================
-- Seed exam questions (run after schema.sql)
-- Run in Supabase SQL Editor to fix "No exam questions available"
-- =============================================

-- English questions (language = 'en')
INSERT INTO public.questions (language, question_text, options, correct_index, category) VALUES
('en', 'What is the speed limit in a residential area unless otherwise posted?', '["20 km/h", "30 km/h", "40 km/h", "50 km/h"]'::jsonb, 2, 'speed'),
('en', 'When must you use your headlights?', '["Only at night", "From sunset to sunrise and when visibility is poor", "Only in rain", "Only on highways"]'::jsonb, 1, 'safety'),
('en', 'What does a solid yellow line on your side of the center line mean?', '["Pass with caution", "Do not pass", "Reduce speed", "Stop"]'::jsonb, 1, 'signs'),
('en', 'Who has the right-of-way at an uncontrolled intersection?', '["The larger vehicle", "The vehicle on the left", "The vehicle on the right", "The first to arrive"]'::jsonb, 2, 'rules'),
('en', 'What should you do when you see a pedestrian crossing at a crosswalk?', '["Speed up to pass before they cross", "Sound your horn", "Yield and allow them to cross", "Change lanes"]'::jsonb, 2, 'pedestrians'),
('en', 'What does a red octagonal sign mean?', '["Yield", "Stop", "No entry", "Caution"]'::jsonb, 1, 'signs'),
('en', 'When driving in fog, you should:', '["Use high beam headlights", "Use low beam headlights", "Drive without lights", "Use hazard lights only"]'::jsonb, 1, 'safety'),
('en', 'What is the legal blood alcohol limit for drivers?', '["0.05%", "0.08%", "0.00%", "0.10%"]'::jsonb, 2, 'alcohol'),
('en', 'Before changing lanes, you should:', '["Speed up", "Check mirrors and blind spots", "Honk twice", "Turn off indicators"]'::jsonb, 1, 'safety'),
('en', 'What does a green traffic light mean?', '["Slow down", "Go if the way is clear", "Stop", "Yield"]'::jsonb, 1, 'signs'),
('en', 'When may you pass on the right?', '["Never", "When the vehicle ahead is turning left and there is room", "Only on one-way streets", "Only when the other driver signals"]'::jsonb, 1, 'rules'),
('en', 'What should you do when approaching a school zone?', '["Honk to warn children", "Reduce speed and watch for children", "Maintain speed", "Change lanes"]'::jsonb, 1, 'safety'),
('en', 'A diamond-shaped sign indicates:', '["Stop", "Yield", "Warning", "Speed limit"]'::jsonb, 2, 'signs'),
('en', 'When parking on a hill with a curb, turn your wheels:', '["Away from the curb", "Toward the curb", "Straight", "It does not matter"]'::jsonb, 1, 'parking'),
('en', 'What does a flashing yellow light mean?', '["Stop", "Go quickly", "Proceed with caution", "Yield to all traffic"]'::jsonb, 2, 'signs'),
('en', 'You must yield to emergency vehicles when they are using sirens and lights by:', '["Speeding up to get out of the way", "Pulling to the right and stopping", "Stopping in your lane", "Honking your horn"]'::jsonb, 1, 'rules'),
('en', 'What is the first thing you should do when your vehicle starts to skid?', '["Brake hard", "Steer in the direction you want to go", "Accelerate", "Turn off the engine"]'::jsonb, 1, 'safety'),
('en', 'When are you allowed to use a mobile phone while driving?', '["Only for texting", "Only when stopped or with hands-free", "Anytime", "Only on highways"]'::jsonb, 1, 'rules'),
('en', 'What does a white line between lanes mean?', '["No passing", "Same direction traffic", "Merge", "Stop ahead"]'::jsonb, 1, 'signs'),
('en', 'Before entering a highway from an entrance ramp, you should:', '["Stop and wait for an opening", "Slow down and yield to traffic", "Accelerate to match the flow of traffic", "Honk and merge quickly"]'::jsonb, 2, 'rules'),
('en', 'What should you do when you see a yellow light?', '["Speed up to get through", "Stop if it is safe to do so", "Always stop", "Honk your horn"]'::jsonb, 1, 'signs'),
('en', 'The best way to avoid fatigue on a long trip is to:', '["Drive faster to finish sooner", "Take regular rest breaks", "Drink caffeine only", "Turn up the radio"]'::jsonb, 1, 'safety'),
('en', 'When two vehicles arrive at an intersection at the same time, the driver on the left must:', '["Proceed first", "Yield to the driver on the right", "Honk", "Speed up"]'::jsonb, 1, 'rules'),
('en', 'What does a blue sign indicate?', '["Warning", "Stop", "Information or services", "Speed limit"]'::jsonb, 2, 'signs'),
('en', 'You should increase your following distance when:', '["Driving in good weather", "The road is dry", "Following a motorcycle", "Driving in bad weather or behind a large vehicle"]'::jsonb, 3, 'safety'),
('en', 'When must you use your turn signals?', '["Only when other cars are present", "At least 100 feet before turning or changing lanes", "Only at night", "Only on highways"]'::jsonb, 1, 'rules'),
('en', 'What does a red triangle sign mean?', '["Stop", "Yield", "No entry", "Wrong way"]'::jsonb, 1, 'signs'),
('en', 'If you miss your exit on a highway, you should:', '["Reverse to the exit", "Stop and back up", "Continue to the next exit", "Make a U-turn"]'::jsonb, 2, 'rules'),
('en', 'When driving at night, you should:', '["Use high beams at all times", "Look at the center of the road", "Reduce speed and increase following distance", "Drive close to the vehicle ahead"]'::jsonb, 2, 'safety'),
('en', 'What is the purpose of an airbag?', '["To replace seat belts", "To reduce the risk of injury in a collision", "To improve fuel economy", "To make the car more comfortable"]'::jsonb, 1, 'safety');

-- Nepali questions (language = 'ne') - same questions in Nepali for ne locale
INSERT INTO public.questions (language, question_text, options, correct_index, category) VALUES
('ne', 'आवासीय क्षेत्रमा अन्यथा पोस्ट नगरेसम्म गति सीमा कति हो?', '["२० किमी/घण्टा", "३० किमी/घण्टा", "४० किमी/घण्टा", "५० किमी/घण्टा"]'::jsonb, 2, 'speed'),
('ne', 'तपाईं कहिले हेडलाइट प्रयोग गर्नुपर्छ?', '["केवल रातमा", "सूर्यास्त देखि सूर्योदय सम्म र दृश्यता कम भएमा", "केवल पानीमा", "केवल राजमार्गमा"]'::jsonb, 1, 'safety'),
('ne', 'केन्द्र रेखाको तपाईंको तर्फको ठोस पहेंलो रेखाले के मतलब राख्छ?', '["सावधानीपूर्वक ओभरटेक गर्नुहोस्", "ओभरटेक नगर्नुहोस्", "गति कम गर्नुहोस्", "रोक्नुहोस्"]'::jsonb, 1, 'signs'),
('ne', 'नियन्त्रण नभएको चौराहामा कसलाई प्राथमिकता छ?', '["ठूलो सवारी", "बायाँ पट्टिको सवारी", "दायाँ पट्टिको सवारी", "पहिले पुग्ने"]'::jsonb, 2, 'rules'),
('ne', 'पदयात्रा क्रसवाकमा पार गर्दा तपाईंले के गर्नुपर्छ?', '["उनीहरू पार हुनु अघि छिटो गर्नुहोस्", "हर्न बजाउनुहोस्", "उनीहरूलाई बाटो दिनुहोस्", "लेन बदल्नुहोस्"]'::jsonb, 2, 'pedestrians'),
('ne', 'रातो अष्टकोण चिन्हले के जनाउँछ?', '["बाटो दिनुहोस्", "रोक्नुहोस्", "प्रवेश निषेध", "सावधान"]'::jsonb, 1, 'signs'),
('ne', 'कुहिरोमा गाडी चलाउँदा तपाईंले:', '["हाई बीम हेडलाइट प्रयोग गर्नुपर्छ", "लो बीम हेडलाइट प्रयोग गर्नुपर्छ", "बत्ती बिना चलाउनुपर्छ", "केवल खतरा बत्ती प्रयोग गर्नुपर्छ"]'::jsonb, 1, 'safety'),
('ne', 'चालकहरूको लागि कानूनी रक्त शराब सीमा कति हो?', '["०.०५%", "०.०८%", "०.००%", "०.१०%"]'::jsonb, 2, 'alcohol'),
('ne', 'लेन बदल्नु अघि तपाईंले:', '["गति बढाउनुपर्छ", "मिरर र ब्लाइन्ड स्पट जाँच गर्नुपर्छ", "दुई पटक हर्न बजाउनुपर्छ", "इन्डिकेटर बन्द गर्नुपर्छ"]'::jsonb, 1, 'safety'),
('ne', 'हरित यातायात बत्तीले के जनाउँछ?', '["गति कम गर्नुहोस्", "बाटो खाली भए जानुहोस्", "रोक्नुहोस्", "बाटो दिनुहोस्"]'::jsonb, 1, 'signs'),
('ne', 'तपाईं कहिले दायाँबाट ओभरटेक गर्न सक्नुहुन्छ?', '["कहिल्यै होइन", "अगाडिको सवारी बायाँ मोड्दा र ठाउँ भएमा", "केवल एकतर्फी सडकमा", "अर्को चालकले सङ्केत गरेमा मात्र"]'::jsonb, 1, 'rules'),
('ne', 'स्कुल जोन नजिक पुग्दा तपाईंले के गर्नुपर्छ?', '["बच्चाहरूलाई चेताउन हर्न बजाउनुहोस्", "गति कम गर्नुहोस् र बच्चाहरूको लागि हेर्नुहोस्", "गति कायम राख्नुहोस्", "लेन बदल्नुहोस्"]'::jsonb, 1, 'safety'),
('ne', 'हरियो हीराक आकारको चिन्हले जनाउँछ:', '["रोक्नुहोस्", "बाटो दिनुहोस्", "चेतावनी", "गति सीमा"]'::jsonb, 2, 'signs'),
('ne', 'कर्ब भएको पहाडमा पार्किङ गर्दा पाङ्ग्रा:', '["कर्बबाट टाढा", "कर्बतर्फ", "सीधा", "केही फरक पर्दैन"]'::jsonb, 1, 'parking'),
('ne', 'झल्कने पहेंलो बत्तीले के जनाउँछ?', '["रोक्नुहोस्", "छिटो जानुहोस्", "सावधानीपूर्वक अगाडि बढ्नुहोस्", "सबै यातायातलाई बाटो दिनुहोस्"]'::jsonb, 2, 'signs'),
('ne', 'सायरन र बत्ती प्रयोग गर्दा इमर्जेन्सी सवारीहरूलाई तपाईंले:', '["बाटो छोड्न छिटो गर्नुपर्छ", "दायाँ पट्टि पुल गरेर रोक्नुपर्छ", "आफ्नो लेनमा रोक्नुपर्छ", "हर्न बजाउनुपर्छ"]'::jsonb, 1, 'rules'),
('ne', 'गाडी स्किड हुन थालेको बेलामा पहिलो के गर्नुपर्छ?', '["कडा ब्रेक लगाउनुहोस्", "तपाईं जान चाहनुभएको दिशामा स्टियर गर्नुहोस्", "एक्सेलरेट गर्नुहोस्", "इन्जिन बन्द गर्नुहोस्"]'::jsonb, 1, 'safety'),
('ne', 'गाडी चलाउँदा मोबाइल फोन कहिले प्रयोग गर्न पाइन्छ?', '["केवल टेक्स्ट गर्न", "केवल रोकेर वा ह्यान्ड्स-फ्री भएमा", "कुनै पनि समय", "केवल राजमार्गमा"]'::jsonb, 1, 'rules'),
('ne', 'लेनहरू बीचको सेतो रेखाले के जनाउँछ?', '["ओभरटेक निषेध", "उही दिशाको यातायात", "मर्ज गर्नुहोस्", "अगाडि रोक्नुहोस्"]'::jsonb, 1, 'signs'),
('ne', 'प्रवेश र्याम्पबाट राजमार्गमा प्रवेश गर्नु अघि तपाईंले:', '["रोकेर खाली ठाउँको पर्खनुहोस्", "गति कम गरेर यातायातलाई बाटो दिनुहोस्", "यातायातको बहावसँग मिल्न एक्सेलरेट गर्नुहोस्", "हर्न बजाएर छिटो मर्ज गर्नुहोस्"]'::jsonb, 2, 'rules'),
('ne', 'पहेंलो बत्ती देख्दा तपाईंले के गर्नुपर्छ?', '["भित्र पस्न छिटो गर्नुहोस्", "सुरक्षित भए रोक्नुहोस्", "सधैं रोक्नुहोस्", "हर्न बजाउनुहोस्"]'::jsonb, 1, 'signs'),
('ne', 'लामो यात्रामा थकान कम गर्ने उत्तम तरिका:', '["छिटो सक्न छिटो चलाउनुहोस्", "नियमित आराम बिरामी लिनुहोस्", "केवल कफी पिउनुहोस्", "रेडियो बढाउनुहोस्"]'::jsonb, 1, 'safety'),
('ne', 'दुई सवारी एकै समयमा चौराहामा पुग्दा बायाँ पट्टिको चालकले:', '["पहिले अगाडि बढ्नुपर्छ", "दायाँ पट्टिको चालकलाई बाटो दिनुपर्छ", "हर्न बजाउनुपर्छ", "गति बढाउनुपर्छ"]'::jsonb, 1, 'rules'),
('ne', 'निलो चिन्हले के जनाउँछ?', '["चेतावनी", "रोक्नुहोस्", "जानकारी वा सेवा", "गति सीमा"]'::jsonb, 2, 'signs'),
('ne', 'तपाईंले पछ्याउने दूरी कहिले बढाउनुपर्छ?', '["राम्रो मौसममा चलाउँदा", "सडक सुख्खा भएमा", "मोटरसाइकल पछ्याउँदा", "नराम्रो मौसम वा ठूलो सवारी पछ्याउँदा"]'::jsonb, 3, 'safety'),
('ne', 'तपाईं कहिले टर्न सिग्नल प्रयोग गर्नुपर्छ?', '["केवल अर्को गाडी भएमा", "मोड्न वा लेन बदल्नु अघि कम्तीमा १०० फिट", "केवल रातमा", "केवल राजमार्गमा"]'::jsonb, 1, 'rules'),
('ne', 'रातो त्रिकोण चिन्हले के जनाउँछ?', '["रोक्नुहोस्", "बाटो दिनुहोस्", "प्रवेश निषेध", "गलत बाटो"]'::jsonb, 1, 'signs'),
('ne', 'राजमार्गमा निकास चुक्नु भएमा तपाईंले:', '["निकासमा पुग्न उल्टिनुहोस्", "रोकेर पछि जानुहोस्", "अर्को निकास सम्म जानुहोस्", "यू-टर्न गर्नुहोस्"]'::jsonb, 2, 'rules'),
('ne', 'रातमा गाडी चलाउँदा तपाईंले:', '["सधैं हाई बीम प्रयोग गर्नुपर्छ", "सडकको बीचमा हेर्नुपर्छ", "गति कम गरेर पछ्याउने दूरी बढाउनुपर्छ", "अगाडिको सवारी नजिक चलाउनुपर्छ"]'::jsonb, 2, 'safety'),
('ne', 'एयरब्यागको उद्देश्य के हो?', '["सीट बेल्टको सट्टा", "टकरावमा चोटको जोखिम कम गर्न", "इन्धन बचत", "गाडी आरामदायक बनाउन"]'::jsonb, 1, 'safety');
